name: Rust

on:
  push:
    branches: [ "master", "production" ]
  pull_request:
    branches: [ "production"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
          matrix:
            node-version: [18.x]
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --release
      
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
  
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Build
      run: |
        cd static/scripts
        npm run build
