name: Rust

on:
  push:
    branches: [ "master", "production" ]
  pull_request:
    branches: [ "production"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
          matrix:
            node-version: [18.x]
    steps:
    - uses: actions/checkout@v3
    
    - name: Use nightly rust
      run: rustup default nightly
      
    - name: Install wasm-pack 
      run: |
        rustup target add asmjs-unknown-emscripten --toolchain nightly
        rustup target add wasm32-unknown-emscripten --toolchain nightly
        cargo install wasm-pack
        
    - name: Build rust for Release
      run: cargo build --release
      
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Bundle JS & Link compiled wasm
      run: |
        cd static/scripts
        npm run build
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Auto-Created Bundle and WASM
