name: Build
on:
  pull_request:
    branches: [ "master"]
env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
          matrix:
            node-version: [18.x]
    steps:
    - uses: actions/checkout@v3
    
    - name: Use nightly rust
      run: rustup default nightly
      
    - name: Build rust for Release
      run: cargo build --release
      
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Bundle JS
      run: |
        cd static/scripts
        npm i && gulp
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Auto-Created Bundle
